# Generated by Django 6.0.5 on 2026-05-18 09:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('management', 'Management'), ('social_media', 'Social Media'), ('performance_marketing', 'Performance Marketing'), ('content', 'Content'), ('production', 'Production'), ('post_production', 'Post Production')], max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('social_media_executive', 'Social Media Executive'), ('performance_marketer', 'Performance Marketer'), ('content_head', 'Content Head'), ('script_writer', 'Script Writer'), ('copy_writer', 'Copy Writer'), ('creator', 'Creator'), ('video_editor', 'Video Editor'), ('designer', 'Designer')], max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.department'),
        ),
    ]
